### PR TITLE
Pyjail

### PR DESCRIPTION
**Pull request by haidark**
initial PR, untested

DO NOT MERGE

### CODE REVIEW

**Comment by haidark** [comment]
@c-rit can you take this implementation up?

**Comment by c-rit** [comment]
> @c-rit can you take this implementation up?

Can do!

**Comment by haidark** [comment]
ready to merge @c-rit ?

**Comment by c-rit** [comment]
> ready to merge @c-rit ?

Player and game have been tested with main. Should be good to go!

**Pull request merged**
